### PR TITLE
#42 feature push notifications

### PR DESCRIPTION
**Pull request by lea88pu**
Push notifications tested, when app is in background or when fully closed it sends messages.
Please review.

### CODE REVIEW

**Review by matejthetree — COMMENTED** [review]
Oke. Nije mi jasno gdje se radi taj firebase notification. Gdje se incijalizira taj servic3?

**Comment by lea88pu** [comment]
@matejthetree U Firebase-u se ide u project, pa Grow, zatim Cloud Messaging i tamo se stavi naslov i sadrzaj poruke, izabere app u koji se poruka salje, vrijeme i send.

**Review by matejthetree — COMMENTED** [review]
Nije mi jasno gdje se inicijalizira `FirebaseNotifications, kao klasa?

**Comment by lea88pu** [comment]
@matejthetree U biti sam zaboravila dodati u main  , ali me sad muci zasto onda radi.. Obrisala sam kompletan dart file firebase push notifications i svejedno primam notifikacije. 
Prouciti cu to da vidim sto se zapravo zbiva.
 Svaka pomoc je dobrodosla.

**Comment by SempaiEcchi** [comment]
Uninstallaj app sa moba

**Comment by matejthetree** [comment]
did you try uninstall app and install again

**Comment by lea88pu** [comment]
@matejthetree I have tried and then i have restarted the app without the dart file and the notification is received.
 It looks like the code is needed for managing other options like pushing the notification when the app is closed or opened.
 In case of only being in background, notification is received.
 Before the push i have had a different code that needed to be slightly adapted (i could receive notification even when the app was closed), after changing the code i have run tests again and everything seamed to work, but now i think i should have deleted the app first and then rerun tests,because it gave me false positive output.
 Anyway I'm still working to solve the issue.

**Comment by matejthetree** [comment]
Cool

**Review by matejthetree — APPROVED** [review]
Rebase then merge

**Comment by SempaiEcchi** [comment]
should I be the one to merge?

**Comment by lea88pu** [comment]
Ja cu,nisam stigla jos

Dana 11. velj 2020. 20:53 osoba "Leo Radocaj" <notifications@github.com>
napisala je:

**Pull request merged**
